name: Deploy to S3

on:
  push:
    branches:
      - main  # This tells the robot to run only when you push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # London region

      - name: Deploy to S3
        run: aws s3 sync . s3://shola-cloud-resume-2026-site --exclude "terraform/*" --exclude ".github/*" --exclude ".git/*"

      - name: Create CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

        